### ISSUE TITLE
Mysql connection not OK

### ISSUE THREAD

**Issue by Jazzbil** [CloudCommandos/Raspclouds#1]
Hi,
Im making new email server on my raspberry pi 3+ Your wiki page is verry helpfull for this moment but i have trouble with mysql connection. in the /www/html/installer/ on web browser i have an error which is the " MySQL:  NOT AVAILABLE "  i tryed to your sql setup instructions but i guess i can't connect it.  i don't how i connect mysql otherway , could you help me or suggest any solution

**Comment by youngee91** [comment]
Hi,
please remove both roundcube and mysql from your machine first.
```
apt purge roundcube mysql-server
apt autoremove
```

Once removed, install mysql first and before installing roundcube. its seems like there's a change in sequence perhaps due to version change.
```
apt install mysql-server
apt install roundcube
```

you should be able to connect to `mysql`. Do let me know should you have anymore problem.

**Comment by Jazzbil** [comment]
Hi,

Thanks for your all efforts. I already make settings according to your shown but still have same problem. I realize that 

`Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 36
Server version: 10.3.17-MariaDB-0+deb10u1 Raspbian 10

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
`
in my terminal.

But your versions are different. It could be problem for that?


Thanks in advance...

**Comment by youngee91** [comment]
Since you are able to start `mysql` can you type `show databases;` and see if a database named roundcube is present?

if not, I suggest you remove roundcube entirely. perhaps I missed out on one of the roundcube packages that was included as well when installing roundcube.
```
apt purge roundcube roundcube-mysql
apt autoremove
```
then install roundcube back `apt install roundcube` . during the installation, did you go into a prompt page to configure the database?

**Comment by Jazzbil** [comment]
`
MariaDB [roundcubemail]> status;
--------------
mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

Connection id:          16
Current database:       roundcubemail
Current user:           root@localhost
SSL:                    Not in use
Current pager:          less
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         10.3.17-MariaDB-0+deb10u1 Raspbian 10
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8mb4
Conn.  characterset:    utf8mb4
UNIX socket:            /var/run/mysqld/mysqld.sock
Uptime:                 14 hours 53 min 8 sec

Threads: 7  Questions: 12  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables: 11  Queries per second avg: 0.000
`

**Comment by youngee91** [comment]
so do you have the database `roundcube` in your mysql database?
